### ISSUE TITLE
ideas for OS

### ISSUE THREAD

**Issue by webcoderz** [nethunteros/manifest#1]
make apps out of simple scripts, like on the pwn phone, i was able to overlay nethunter onto pwn phone i know its kind of rendundant but then you get the best of both worlds. I like the idea they have of having the different tools as apps, like they have a metasploit app, ettercap, SET, airodump, and they are all configured already so its just turnkey.  any thoughts?  they have AOPP now thats open source.

**Comment by webcoderz** [comment]
i guess a GUI essentially

**Comment by binkybear** [comment]
Hi @akrolla ,

Right now I'm focused on getting a working version mainly to support nexmon (built in monitor mode).  I don't plan on making different apps for each script, we have an add a custom command in nethunter app for that.

I haven't looked at the Pwnie stuff in a long time.  Very neat you got them working together.  I know they have a CM fork but I've never even looked at their source.  I have a working Nexus 5 (cm 14.1) from this repo and it needs a little bit of tweaking.  

I don't know if this will be future of updates but for now this is more of just an experiment and learning experience.

**Comment by webcoderz** [comment]
understandable. i was envisioning a pwnie like experience for this, when i saw it . instead of making frankenstein kernels to adapt to the ecosystem.. why not just make the ecosystem, then OTA updates could be done, and with the GUI look , you could build an app store with diff scripts with a sweet little logos . I think it would be possible, i know NH pretty much does all of the above, but i see all the issues you guys have from all the different devices and think that having control over the whole ecosystem would help mitigate some of the issues.

**Comment by webcoderz** [comment]
nexmon would sure be awesome for my little old nexus 5 =-o ,

**Comment by webcoderz** [comment]
Since aopp is open source now, you could add it as a kernel since it has the 3.4 kernel and figure a way to have the scripts of the gui connect to the chroot so you don't have to have 2 , then you could use nethunter for more advanced attacks as the basic scipts are taken carw of in a nice gui representation gives it a more OS feel

**Comment by webcoderz** [comment]
I'm jist providing suggestions.. sorry , I think an entire OS would really make Kali stand out.

**Comment by webcoderz** [comment]
Were practically. Over half way to a full os and then focus can be put on the net hunter app for more advanced attacks. When I installed nethunter overlay the pwnix commands go thru root@kali

**Comment by webcoderz** [comment]
nvm the network access name changed automatically

**Comment by webcoderz** [comment]
@binkybear is it going to be possible to overlay that nexus 5 nethunter0s overthe pwnphone i have unstalled also with nethunter? or  how would you do it or what would yo do?

**Comment by webcoderz** [comment]
or I would like to extract all the scripts and icons for those scripts out of aopp, link them to kali chroot and whatever other non proprietary scripts from aopp, or how can you link all the aopp stuff to the kali chroot in nh or vice versa becaude aopps kernel is 3.4??

**Comment by webcoderz** [comment]
so I don't have to have 2 chroots. downloading the new. OS now maybe you've already answered some of these questions already..another question where would I put the poisontap script or mubix scripts in. NHs chroot?

**Comment by binkybear** [comment]
akrolla - I have no experience with the AOPP stuff (never seen it).  I don't plan on integrating support to AOPP since I feel like our app covers most of what the other one probably does (redundant and more work for me).  It would be a lot of work and testing to get both to play together and I just don't have the time at the moment.

The mubix script already exists in your /usr/bin/mubix-lock.sh in chroot.  It's located in nethunter-utils packages in kali.  As long as you have that installed it will work.

Posiontap is still untested.

**Comment by webcoderz** [comment]
ok i dont have that installed thanks. i was just thinking more or less putting a face to the various scripts thats the only diff between what your doing and there doing.

**Comment by webcoderz** [comment]
when you click on one of there apps, lets say ettercap, it just is a bash script with a pretty picture, they did all the leg work for people like me who are inexperienced with all of the arguments that you have to enter into the different programs, i guess its kinda designed for script kidies when u  think of it... , alls it does when you click on it is open a terminal, and it has the thats what i mean, sorry i tend to confuse people because i go off on tangents, NH can do all of what pwn phone and more it just doesnt have a fancy UI its for people who are good in terminals, PWNIE essentially made a hacker IPHONE... like i said a while ago im still a noob and i dont know much about android, but im focusing on learning python, as i would like to help contribute like you do to the project if you let me when i get better:) i learn a lot just reading some of the stuff you code.

**Comment by webcoderz** [comment]
would you be cool with me making a flash-all.bat for the nexus 5 NHOS?

**Comment by webcoderz** [comment]
i got them playing together, i just dont know how to intertwine the chroots, to save space for the phone, and also they have root for each of their apps. so im unsure there also
.
im glad to be in the graces of a legend tho so thanks for puttin up with my sometimes off the wall questions or comments .

**Comment by webcoderz** [comment]
because remember when you came out with the KALI PWN PAD they incorporated your chroot into it in the 2013 grouper version whereas befre it was ubuntu touch.

**Comment by webcoderz** [comment]
i mut be doing something wrong with the mubix script because i updated nethunter-utils and it still isnt showing up,  using v 3.15 NH app

**Comment by webcoderz** [comment]
is the nexmon in the chroot? i could just essentially swap them out on my nexus5 kali pwn phone right and the nexmon should work in kali terminal? or do all the parts have to be in play for it to work?

**Comment by binkybear** [comment]
Nexmon is outside the chroot.  You could also use nexmon app on your other phone.  It probably won't work inside chroot though.  There are specific kernel patches that needed to be applied.
